<?php

namespace Wefabric\FormCache\Providers;

use Wefabric\FormCache\Console\Commands\FormCacheGarbageCollection;

class ServiceProvider extends \Illuminate\Support\ServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        $this->publishes([
            __DIR__.'/../../database/migrations/' => database_path('migrations')
        ], ['wefabric_form_cache', 'migrations']);

        $this->publishes([
            __DIR__.'/../../config/form-cache.php' => config_path('form-cache.php'),
        ], ['wefabric_form_cache', 'config']);

        if ($this->app->runningInConsole()) {
            $this->commands([
                FormCacheGarbageCollection::class
            ]);
        }
    }
}
